import { auth } from "./auth";

const IDS = [
  "adriana.santos@objectedge.com",
  "adriano.zanette@objectedge.com",
  "ana.franciosi@objectedge.com",
  "anas.abdulrjab@objectedge.com",
  "andre.costa@objectedge.com",
  "anibal.deus@objectedge.com",
  "antonio.filho@objectedge.com",
  "breno.meneghetti@objectedge.com",
  "bruno.farias@objectedge.com",
  "caetano.almeida@objectedge.com",
  "carlos.flores@objectedge.com",
  "carlos.kerber@objectedge.com",
  "carlos.mega@objectedge.com",
  "caroline.rosa@objectedge.com",
  "cinthia.modesto@objectedge.com",
  "daniel.dallagnese@objectedge.com",
  "diego.demarco@objectedge.com",
  "douglas.davila@objectedge.com",
  "dyonata.ramos@objectedge.com",
  "edith.burgos@objectedge.com",
  "emilio.bresolin@objectedge.com",
  "felipe.alves@objectedge.com",
  "felipe.nunes@objectedge.com",
  "fernanda.marques@objectedge.com",
  "fernando.cardozo@objectedge.com",
  "fernando.croccoli@objectedge.com",
  "giuliano.riboni@objectedge.com",
  "gustavo.farias@objectedge.com",
  "glauciany.santos@objectedge.com",
  "guilherme.bragamonte@objectedge.com",
  "guilherme.fontes@objectedge.com",
  "henrique.schuster@objectedge.com",
  "igor.nascimento@objectedge.com",
  "jader.belarmino@objectedge.com",
  "jose.colpo@objectedge.com",
  "julian.sotuyo@objectedge.com",
  "juliana.wolfarth@objectedge.com",
  "keith.sarate@objectedge.com",
  "leandro.souza@objectedge.com",
  "leonardo.lothamer@objectedge.com",
  "leticia.daniel@objectedge.com",
  "luan.rosa@objectedge.com",
  "lucas.carneiro@objectedge.com",
  "luciano.burger@objectedge.com",
  "marcelo.goncalves@objectedge.com",
  "marcelo.joras@objectedge.com",
  "mario.sanseverino@objectedge.com",
  "mauricio.neto@objectedge.com",
  "moacir.zardo@objectedge.com",
  "nilton.santos@objectedge.com",
  "patricia.nardelli@objectedge.com",
  "paulo.gross@objectedge.com",
  "paulo.soares@objectedge.com",
  "pedro.franco@objectedge.com",
  "rafael.lopes@objectedge.com",
  "rafael.matos@objectedge.com",
  "rafael.sarate@objectedge.com",
  "rafael.souza@objectedge.com",
  "renan.silva@objectedge.com",
  "rigel.marroquin@objectedge.com",
  "samantha.costa@objectedge.com",
  "taiara.regis@objectedge.com",
  "thaine.abich@objectedge.com",
  "valmor.castro@objectedge.com",
  "vanessa.posso@objectedge.com",
  "walter.neto@objectedge.com",
  "yann.buffet@objectedge.com",
];

export default async function canVote() {
  const id = (await auth())?.user?.email;
  return id && IDS.includes(id);
}
